version: '3'

networks:
  virt-manager:
    driver:
      bridge
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: "172.1.0.0/16"

services:  
  virt-manager:
    build: .
    container_name: virt-manager
    image: docker-virt-manager
    restart: always
    ports:
      - 8185:80
    networks:
      - virt-manager
    environment:
      HOSTS: "[]"
      DOMINIO: ""
      HOST_DOMINIO_1: ""
      HOST_DOMINIO_2: ""

    volumes:
      - ./keys/chave.pem:/root/.ssh/chave.pem:ro
