services: 
  
  virt-manager:
    container_name: virt-manager
    image: docker-virt-manager
    restart: always
    ports:
      - 8185:80

    environment:
      HOSTS: "[]"
      DOMINIO: ""
      HOST_DOMINIO_1: ""
      HOST_DOMINIO_2: ""

    volumes:
      - ./keys/chave.pem:/root/.ssh/chave.pem:ro