version: '3'

networks:
  virt-manager:
    driver:
      bridge

services:  
  virt-manager:
    build:
      dockerfile: ./DockerFile
      context: .
    container_name: virt-manager
    image: docker-virt-manager
    restart: always
    ports:
      - 8185:80
    networks:
      - virt-manager
    environment:
      HOSTS: "[]"
      DOMINIO: ""
      HOST_DOMINIO_1: ""
      HOST_DOMINIO_2: ""

    volumes:
      - ./keys/chave.pem:/root/.ssh/chave.pem:ro